# Generated by Django 3.1.7 on 2021-06-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
