# Generated by Django 3.1.7 on 2021-05-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0003_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
