# Generated by Django 3.1.7 on 2021-06-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0005_auto_20210531_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='student_resumes',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
