# Generated by Django 3.1.7 on 2021-06-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0006_recruiter_student_resumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='applied_student',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
