# Generated by Django 3.1.7 on 2021-06-01 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0007_recruiter_applied_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiter',
            name='applied_student',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='student_resumes',
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_resumes', models.FileField(null=True, upload_to='')),
                ('applied_student', models.CharField(max_length=20, null=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlinejobportalApp.recruiter')),
            ],
        ),
    ]
