# Generated by Django 3.1.7 on 2021-06-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0008_auto_20210601_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='recruiter',
        ),
    ]
