# Generated by Django 3.1.7 on 2021-06-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlinejobportalApp', '0009_remove_apply_recruiter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='applied_student',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='tudent_resumes',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
